/** Shared dark sportsbook UI tokens (inline styles for Vite/React). */
export const styles = {
  page: {
    maxWidth: "1100px",
    margin: "0 auto",
    padding: "12px 12px 48px",
    width: "100%",
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "10px",
    marginBottom: "12px",
  },
  eyebrow: { margin: 0, color: "#64748b", fontSize: "11px", fontWeight: 800, textTransform: "uppercase" },
  title: { margin: "4px 0 0", fontSize: "clamp(20px, 5vw, 28px)", lineHeight: 1.1 },
  subtitle: { margin: "6px 0 0", color: "#94a3b8", fontSize: "13px", lineHeight: 1.4, maxWidth: "520px" },
  lastUpdated: { margin: "6px 0 0", color: "#64748b", fontSize: "12px" },
  refreshButton: {
    border: "1px solid #22c55e",
    background: "#14532d",
    color: "#dcfce7",
    borderRadius: "8px",
    padding: "10px 14px",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: "13px",
    whiteSpace: "nowrap",
  },
  streakControls: { marginBottom: "10px" },
  streakTitle: { margin: "4px 0 0", fontSize: "18px" },
  streakCopy: { margin: "4px 0 0", color: "#94a3b8", fontSize: "12px" },
  streakNotice: { margin: "8px 0 0", color: "#7dd3fc", fontSize: "12px" },
  segmentGroup: { display: "grid", gap: "6px", marginTop: "8px" },
  controlLabel: { color: "#94a3b8", fontSize: "11px", fontWeight: 800, textTransform: "uppercase" },
  segmentRow: { display: "flex", flexWrap: "wrap", gap: "6px" },
  segment: {
    border: "1px solid #334155",
    background: "#111827",
    color: "#cbd5e1",
    borderRadius: "8px",
    padding: "8px 10px",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: "12px",
  },
  segmentActive: {
    border: "1px solid #22c55e",
    background: "#14532d",
    color: "#dcfce7",
    borderRadius: "8px",
    padding: "8px 10px",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: "12px",
  },
  errorPanel: {
    padding: "10px",
    border: "1px solid #991b1b",
    background: "#450a0a",
    color: "#fecaca",
    borderRadius: "8px",
    marginBottom: "10px",
    fontSize: "13px",
  },
  warningPanel: {
    padding: "10px",
    border: "1px solid #b45309",
    background: "#451a03",
    color: "#fde68a",
    borderRadius: "8px",
    marginBottom: "10px",
    fontSize: "13px",
  },
  section: { marginTop: "14px" },
  sectionHeading: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
    marginBottom: "8px",
    flexWrap: "wrap",
  },
  sectionTitle: { margin: 0, fontSize: "18px" },
  sectionTitleSmall: { margin: 0, fontSize: "16px" },
  countPill: {
    margin: 0,
    padding: "6px 9px",
    borderRadius: "999px",
    background: "#111827",
    color: "#cbd5e1",
    border: "1px solid #334155",
    fontSize: "12px",
    fontWeight: 800,
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(100%, 280px), 1fr))",
    gap: "8px",
  },
  cardGridCompact: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(min(100%, 260px), 1fr))",
    gap: "5px",
  },
  topPicksList: { display: "grid", gap: "6px" },
  mlbOutlookGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "7px",
  },
  mlbOutlookCard: {
    border: "1px solid #243244",
    background: "linear-gradient(180deg, #111827 0%, #0f172a 100%)",
    borderRadius: "12px",
    padding: "8px",
    minWidth: 0,
    cursor: "pointer",
    boxShadow: "0 1px 0 rgba(148, 163, 184, 0.08)",
    transition: "border-color 0.15s ease, transform 0.15s ease",
  },
  mlbOutlookHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "8px",
  },
  streakCard: { borderColor: "#2563eb", background: "#0b1224" },
  underdogRowList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  underdogRowCard: {
    display: "flex",
    alignItems: "stretch",
    justifyContent: "space-between",
    gap: "10px",
    padding: "10px 12px",
    borderRadius: "10px",
    border: "1px solid #1e293b",
    background: "#0b1220",
    cursor: "pointer",
    minWidth: 0,
  },
  underdogRowLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flex: 1,
    minWidth: 0,
  },
  underdogRowMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    minWidth: 0,
    flex: 1,
  },
  underdogRowNameLine: {
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    flexWrap: "wrap",
  },
  underdogRowPlayer: {
    margin: 0,
    fontSize: "15px",
    fontWeight: 800,
    color: "#f8fafc",
    lineHeight: 1.2,
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  underdogRowRank: {
    fontSize: "10px",
    fontWeight: 800,
    color: "#60a5fa",
    letterSpacing: "0.04em",
  },
  underdogRowLine: {
    fontSize: "18px",
    fontWeight: 900,
    color: "#e2e8f0",
    lineHeight: 1,
  },
  underdogRowMatchup: {
    margin: 0,
    fontSize: "12px",
    fontWeight: 700,
    color: "#94a3b8",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  underdogRowTime: {
    margin: 0,
    fontSize: "11px",
    fontWeight: 600,
    color: "#64748b",
  },
  underdogRowActions: {
    display: "flex",
    gap: "6px",
    flexShrink: 0,
    alignItems: "stretch",
  },
  underdogSideBtn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "2px",
    minWidth: "68px",
    padding: "8px 10px",
    borderRadius: "8px",
    border: "1px solid #334155",
    background: "#111827",
    color: "#cbd5e1",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  underdogSideBtnActive: {
    borderColor: "#22c55e",
    background: "#052e16",
    boxShadow: "0 0 0 1px rgba(34, 197, 94, 0.35)",
  },
  underdogSideLabel: {
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: "0.03em",
    textTransform: "uppercase",
    color: "#e2e8f0",
  },
  underdogSideMultiplier: {
    fontSize: "13px",
    fontWeight: 900,
    color: "#f8fafc",
    lineHeight: 1.1,
  },
  underdogSideProb: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#94a3b8",
    lineHeight: 1.1,
  },
  underdogStatTabs: {
    display: "flex",
    gap: "6px",
    overflowX: "auto",
    paddingBottom: "8px",
    marginBottom: "4px",
    WebkitOverflowScrolling: "touch",
  },
  underdogStatTab: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 10px",
    borderRadius: "999px",
    border: "1px solid #334155",
    background: "#0f172a",
    color: "#94a3b8",
    fontSize: "11px",
    fontWeight: 700,
    whiteSpace: "nowrap",
    cursor: "pointer",
    fontFamily: "inherit",
    flexShrink: 0,
  },
  underdogStatTabActive: {
    borderColor: "#2563eb",
    background: "#172554",
    color: "#dbeafe",
  },
  underdogStatTabCount: {
    fontSize: "10px",
    fontWeight: 800,
    color: "#60a5fa",
  },
  bestPlayRowList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  bestPlayRowCard: {
    display: "flex",
    alignItems: "stretch",
    justifyContent: "space-between",
    gap: "12px",
    padding: "10px 12px",
    borderRadius: "10px",
    border: "1px solid #1e293b",
    background: "#0b1220",
    cursor: "pointer",
    minWidth: 0,
  },
  bestPlayRowLeft: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    flex: 1,
    minWidth: 0,
  },
  bestPlayRowMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    minWidth: 0,
    flex: 1,
  },
  bestPlayRowTopLine: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  bestPlayRowRank: {
    fontSize: "10px",
    fontWeight: 800,
    color: "#60a5fa",
  },
  bestPlayRowPlayer: {
    margin: 0,
    fontSize: "15px",
    fontWeight: 800,
    color: "#f8fafc",
  },
  bestPlayPlatformBadge: {
    fontSize: "10px",
    fontWeight: 800,
    padding: "2px 8px",
    borderRadius: "999px",
    letterSpacing: "0.03em",
    textTransform: "uppercase",
  },
  bestPlayRowSubline: {
    margin: 0,
    fontSize: "12px",
    fontWeight: 600,
    color: "#94a3b8",
  },
  bestPlayRowReason: {
    margin: 0,
    fontSize: "11px",
    lineHeight: 1.4,
    color: "#64748b",
  },
  bestPlayRowMetrics: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: "4px",
    flexShrink: 0,
  },
  bestPlaySideBadge: {
    padding: "4px 10px",
    borderRadius: "8px",
    fontSize: "11px",
    fontWeight: 900,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  bestPlayMetric: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#94a3b8",
    whiteSpace: "nowrap",
  },
  whyPickBlock: {
    marginTop: "4px",
    padding: "6px 8px",
    borderRadius: "6px",
    border: "1px solid #1e3a2f",
    background: "#071510",
  },
  whyPickTitle: {
    display: "block",
    fontSize: "9px",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#86efac",
    marginBottom: "2px",
  },
  whyPickCopy: {
    margin: 0,
    fontSize: "11px",
    lineHeight: 1.35,
    color: "#cbd5e1",
  },
  badgeRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "4px",
    marginTop: "4px",
  },
  scoreBadge: {
    fontSize: "9px",
    fontWeight: 800,
    padding: "2px 6px",
    borderRadius: "999px",
    border: "1px solid #334155",
    background: "#1e293b",
    color: "#e2e8f0",
    letterSpacing: "0.03em",
  },
  card: {
    border: "1px solid #243244",
    background: "#0f172a",
    borderRadius: "8px",
    padding: "8px",
    minWidth: 0,
    cursor: "pointer",
    transition: "border-color 0.15s ease, transform 0.15s ease, box-shadow 0.15s ease",
  },
  cardMobileTight: {
    padding: "3px 4px",
    borderRadius: "6px",
  },
  cardInlineDetails: {
    marginTop: "4px",
    borderTop: "1px solid #1e293b",
    paddingTop: "2px",
  },
  cardInlineSummary: {
    cursor: "pointer",
    color: "#64748b",
    fontSize: "10px",
    fontWeight: 700,
    listStyle: "none",
    userSelect: "none",
  },
  cardInlineBody: {
    marginTop: "4px",
  },
  watchlistCard: { borderColor: "#3f3f46", background: "#111827" },
  goblinCard: { borderColor: "#0d9488", background: "linear-gradient(180deg, #042f2e 0%, #071a12 100%)" },
  demonCard: { borderColor: "#c026d3", background: "linear-gradient(180deg, #3b0764 0%, #1f1308 100%)" },
  featuredBestCard: { borderColor: "#2563eb", background: "linear-gradient(180deg, #0b1224 0%, #0f172a 100%)" },
  featuredEdgeCard: { borderColor: "#ea580c", background: "linear-gradient(180deg, #431407 0%, #1f1308 100%)" },
  featuredSafeCard: { borderColor: "#059669", background: "linear-gradient(180deg, #064e3b 0%, #071a12 100%)" },
  parlayCard: { borderColor: "#4f46e5", background: "#11152a" },
  compactCardTop: { display: "flex", gap: "5px", alignItems: "flex-start", marginBottom: "2px" },
  cardInfo: { minWidth: 0, flex: 1 },
  cardTitleRow: { display: "flex", justifyContent: "space-between", gap: "8px", alignItems: "flex-start" },
  cardBadgeColumn: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: "4px" },
  platform: { margin: "0 0 2px", color: "#22c55e", fontWeight: 900, fontSize: "9px", textTransform: "uppercase" },
  playerName: { margin: 0, fontSize: "15px", fontWeight: 900, lineHeight: 1.15, color: "#f8fafc" },
  gameLine: { margin: "2px 0 0", color: "#94a3b8", fontSize: "11px" },
  compactMetaRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px 12px",
    fontSize: "11px",
    color: "#cbd5e1",
    borderTop: "1px solid #1f2937",
    paddingTop: "6px",
  },
  compactMetaItem: { display: "flex", gap: "4px", alignItems: "baseline" },
  metaLabel: { color: "#64748b", fontSize: "10px", textTransform: "uppercase" },
  metaValueStrong: { color: "#f8fafc", fontWeight: 800 },
  whyLink: {
    marginTop: "6px",
    paddingTop: "6px",
    borderTop: "1px solid #1f2937",
    color: "#7dd3fc",
    fontSize: "11px",
    fontWeight: 800,
  },
  rankBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "28px",
    height: "22px",
    borderRadius: "6px",
    background: "#1e3a5f",
    color: "#93c5fd",
    fontSize: "11px",
    fontWeight: 900,
    marginRight: "6px",
  },
  riskPill: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "999px",
    padding: "4px 8px",
    fontSize: "10px",
    fontWeight: 900,
  },
  dataQualityBadge: {
    display: "inline-block",
    fontSize: "9px",
    fontWeight: 800,
    padding: "2px 6px",
    borderRadius: "999px",
    border: "1px solid transparent",
  },
  dataBadgeFull: { color: "#052e16", background: "#86efac", borderColor: "#22c55e" },
  dataBadgePartial: { color: "#422006", background: "#fde68a", borderColor: "#ca8a04" },
  dataBadgeFallback: { color: "#431407", background: "#fdba74", borderColor: "#ea580c" },
  dataBadgeWeak: { color: "#450a0a", background: "#fca5a5", borderColor: "#ef4444" },
  playerImageWrap: {
    flex: "0 0 36px",
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    overflow: "hidden",
    background: "#111827",
    border: "1px solid #263449",
  },
  playerImageWrapLarge: { flexBasis: "56px", width: "56px", height: "56px" },
  playerImage: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  playerInitials: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    fontWeight: 900,
    fontSize: "12px",
    color: "#e2e8f0",
    background: "#1e293b",
  },
  emptyState: {
    minHeight: "44px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 10px",
    border: "1px dashed #334155",
    borderRadius: "6px",
    color: "#cbd5e1",
    background: "#0f172a",
    textAlign: "center",
    fontSize: "12px",
  },
  emptyStateCompact: {
    minHeight: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "6px 8px",
    border: "1px dashed #334155",
    borderRadius: "6px",
    color: "#94a3b8",
    background: "#0f172a",
    textAlign: "center",
    fontSize: "11px",
  },
  apiHealthPanel: {
    border: "1px solid #1e293b",
    background: "#0b1220",
    borderRadius: "10px",
    padding: "10px",
    marginBottom: "10px",
    display: "grid",
    gap: "8px",
  },
  apiHealthHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
  },
  apiHealthTitle: { fontSize: "13px", color: "#e2e8f0" },
  apiHealthDevTag: {
    fontSize: "10px",
    fontWeight: 800,
    color: "#fcd34d",
    border: "1px solid #ca8a04",
    borderRadius: "999px",
    padding: "2px 8px",
    background: "#422006",
  },
  apiHealthGrid: {
    display: "grid",
    gap: "6px",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
  },
  apiHealthRow: {
    border: "1px solid #1e293b",
    borderRadius: "8px",
    padding: "8px",
    background: "#111827",
    display: "grid",
    gap: "4px",
  },
  apiHealthRowTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "6px",
  },
  debugPre: {
    margin: "6px 0 0",
    padding: "8px",
    background: "#0f172a",
    border: "1px solid #1e293b",
    borderRadius: "8px",
    color: "#94a3b8",
    fontSize: "11px",
    overflowX: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  apiHealthMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    color: "#94a3b8",
    fontSize: "11px",
    alignItems: "center",
  },
  lineSourceBadge: (badge) => {
    const key = String(badge || "").toUpperCase();
    const palette =
      key === "LIVE"
        ? { color: "#14532d", background: "#22c55e", border: "#16a34a", text: "#dcfce7" }
        : key === "CACHED"
          ? { color: "#422006", background: "#fcd34d", border: "#ca8a04", text: "#1f2937" }
          : { color: "#450a0a", background: "#fb7185", border: "#f43f5e", text: "#fff1f2" };
    return {
      fontSize: "10px",
      fontWeight: 800,
      padding: "2px 6px",
      borderRadius: "6px",
      border: `1px solid ${palette.border}`,
      background: palette.background,
      color: palette.text,
      letterSpacing: "0.04em",
    };
  },
  sourceStatusBar: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    marginTop: "10px",
    padding: "8px",
    border: "1px solid #1f2937",
    background: "#0b1220",
    borderRadius: "8px",
  },
  sourceStatusItem: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 8px",
    borderRadius: "6px",
    background: "#111827",
    fontSize: "11px",
  },
  sourceName: { color: "#94a3b8", fontWeight: 700 },
  sourceStatusPill: {
    borderRadius: "999px",
    padding: "2px 7px",
    fontSize: "10px",
    fontWeight: 800,
    border: "1px solid #334155",
  },
  compactDetails: {
    marginTop: "10px",
    border: "1px solid #1f2937",
    background: "#0b1220",
    borderRadius: "8px",
    padding: "8px",
  },
  detailsSummary: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    listStyle: "none",
    fontSize: "13px",
  },
  compactPanel: { marginTop: "8px" },
  controls: { display: "grid", gap: "10px" },
  quickFilters: { marginTop: "8px" },
  selectLabel: { display: "grid", gap: "6px", color: "#cbd5e1", fontSize: "11px", fontWeight: 800, textTransform: "uppercase" },
  select: {
    width: "100%",
    minHeight: "38px",
    borderRadius: "8px",
    border: "1px solid #334155",
    background: "#111827",
    color: "#f8fafc",
    padding: "0 10px",
    fontSize: "13px",
  },
  textInput: {
    width: "100%",
    minHeight: "38px",
    borderRadius: "8px",
    border: "1px solid #334155",
    background: "#111827",
    color: "#f8fafc",
    padding: "0 10px",
    fontSize: "13px",
    boxSizing: "border-box",
  },
  textArea: {
    width: "100%",
    minHeight: "96px",
    borderRadius: "8px",
    border: "1px solid #334155",
    background: "#111827",
    color: "#f8fafc",
    padding: "10px",
    fontSize: "13px",
    boxSizing: "border-box",
    resize: "vertical",
  },
  summaryStrip: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: "6px",
    marginTop: "12px",
  },
  summaryCard: {
    display: "grid",
    gap: "2px",
    border: "1px solid #1f2937",
    background: "#0b1220",
    borderRadius: "8px",
    padding: "8px",
  },
  summaryHint: { color: "#94a3b8", fontSize: "10px" },
  metricLabel: { color: "#94a3b8", fontSize: "10px" },
  compactFlags: { margin: "6px 0 0", color: "#94a3b8", fontSize: "11px" },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: "0",
    background: "rgba(2, 6, 23, 0.85)",
  },
  modalPanel: {
    width: "100%",
    maxWidth: "640px",
    maxHeight: "92vh",
    overflowY: "auto",
    border: "1px solid #334155",
    background: "#0f172a",
    borderRadius: "12px 12px 0 0",
    padding: "14px",
    boxShadow: "0 -8px 40px rgba(0,0,0,.5)",
  },
  modalHeader: { display: "flex", justifyContent: "space-between", gap: "10px", marginBottom: "10px" },
  modalPlayer: { display: "flex", gap: "10px", minWidth: 0, flex: 1 },
  modalTitle: { margin: 0, fontSize: "20px", lineHeight: 1.1 },
  closeButton: {
    border: "1px solid #475569",
    background: "#1e293b",
    color: "#f8fafc",
    borderRadius: "10px",
    padding: "12px 18px",
    minWidth: "72px",
    minHeight: "44px",
    cursor: "pointer",
    fontWeight: 900,
    fontSize: "15px",
    flexShrink: 0,
  },
  tagRow: { display: "flex", flexWrap: "wrap", gap: "5px", marginBottom: "10px" },
  valueTag: {
    border: "1px solid #0e7490",
    background: "#082f49",
    color: "#bae6fd",
    borderRadius: "999px",
    padding: "4px 7px",
    fontSize: "10px",
    fontWeight: 900,
  },
  modalGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: "8px",
  },
  metric: { borderTop: "1px solid #1f2937", paddingTop: "5px" },
  metricValue: { display: "block", color: "#e2e8f0", fontSize: "12px" },
  metricValueStrong: { display: "block", color: "#f8fafc", fontSize: "13px", fontWeight: 800 },
  explanationSections: { display: "grid", gap: "8px", marginTop: "10px" },
  explanationBlock: {
    border: "1px solid #263449",
    background: "#0b1220",
    borderRadius: "8px",
    padding: "8px",
    color: "#dbeafe",
    fontSize: "12px",
  },
  explanationList: { margin: "4px 0 0", paddingLeft: "16px", lineHeight: 1.4 },
  evaluationText: {
    marginTop: "10px",
    padding: "10px",
    border: "1px solid #263449",
    background: "#0b1220",
    borderRadius: "8px",
    color: "#dbeafe",
    fontSize: "13px",
    lineHeight: 1.45,
  },
  comparisonBox: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px",
    marginTop: "10px",
    padding: "8px",
    background: "#111827",
    border: "1px solid #263449",
    borderRadius: "8px",
    fontSize: "12px",
    color: "#cbd5e1",
  },
  watchlistMessage: {
    marginTop: "10px",
    padding: "8px",
    border: "1px solid #334155",
    background: "#0b1220",
    borderRadius: "8px",
    fontSize: "12px",
    color: "#cbd5e1",
  },
  dashboardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(100px, 1fr))",
    gap: "8px",
    marginTop: "10px",
  },
  metricCard: { border: "1px solid #243244", background: "#0f172a", borderRadius: "8px", padding: "10px" },
  dashboardValue: { display: "block", marginTop: "2px", fontSize: "22px" },
  historyFilters: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: "8px",
    margin: "10px 0",
  },
  breakdownGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "8px",
  },
  breakdownCard: { border: "1px solid #243244", background: "#0f172a", borderRadius: "8px", padding: "10px" },
  breakdownTitle: { margin: "0 0 8px", fontSize: "14px" },
  breakdownEmpty: { margin: 0, color: "#94a3b8", fontSize: "12px" },
  breakdownRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
    padding: "6px 0",
    borderTop: "1px solid #1f2937",
    fontSize: "12px",
    color: "#cbd5e1",
  },
  historyList: { display: "grid", gap: "8px", marginTop: "10px" },
  historyRow: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    border: "1px solid #243244",
    background: "#0f172a",
    borderRadius: "8px",
    padding: "10px",
  },
  historyMeta: { margin: "4px 0 0", color: "#94a3b8", fontSize: "12px" },
  resultButtons: { display: "flex", flexWrap: "wrap", gap: "5px" },
  dashboardActions: { display: "flex", flexWrap: "wrap", gap: "6px", alignItems: "center" },
  secondaryButton: {
    border: "1px solid #334155",
    background: "#111827",
    color: "#cbd5e1",
    borderRadius: "8px",
    padding: "7px 9px",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: "12px",
  },
  resultButton: {
    border: "1px solid #334155",
    background: "#111827",
    color: "#cbd5e1",
    borderRadius: "8px",
    padding: "6px 8px",
    cursor: "pointer",
    fontWeight: 800,
    fontSize: "11px",
  },
  resultButtonActive: {
    border: "1px solid #22c55e",
    background: "#14532d",
    color: "#dcfce7",
    borderRadius: "8px",
    padding: "6px 8px",
    cursor: "pointer",
    fontWeight: 900,
    fontSize: "11px",
  },
  watchlistSummary: {
    marginTop: "10px",
    padding: "8px",
    border: "1px solid #1f2937",
    background: "#0b1220",
    borderRadius: "8px",
  },
};

export function tierStyle(tier) {
  const base = { ...styles.riskPill };
  if (tier === "Elite verified" || tier === "Elite") return { ...base, color: "#052e16", background: "#86efac" };
  if (tier === "Strong") return { ...base, color: "#042f2e", background: "#5eead4" };
  if (tier === "Solid" || tier === "Medium") return { ...base, color: "#422006", background: "#facc15" };
  if (tier === "Weak lean") return { ...base, color: "#1e3a5f", background: "#93c5fd" };
  return { ...base, color: "#450a0a", background: "#fca5a5" };
}

export function sourceStatusStyle(status) {
  const base = { ...styles.sourceStatusPill };
  const s = String(status || "");
  if (s === "Connected" || s === "Full" || s === "fresh") return { ...base, color: "#052e16", background: "#86efac", borderColor: "#22c55e" };
  if (/partial|fallback|cached/i.test(s)) return { ...base, color: "#422006", background: "#fcd34d", borderColor: "#ca8a04" };
  if (s === "Failed" || s === "Not Connected") return { ...base, color: "#fecaca", background: "#450a0a", borderColor: "#991b1b" };
  return { ...base, color: "#cbd5e1", background: "#111827", borderColor: "#334155" };
}

export function riskStyle(risk) {
  const base = { ...styles.riskPill };
  const key = String(risk || "").toUpperCase();
  if (key === "LOW" || risk === "Elite") return { ...base, color: "#052e16", background: "#86efac" };
  if (key === "MEDIUM" || risk === "Medium") return { ...base, color: "#422006", background: "#facc15" };
  return { ...base, color: "#450a0a", background: "#fca5a5" };
}

export function dataBadgeStyle(tone) {
  const map = {
    full: styles.dataBadgeFull,
    partial: styles.dataBadgePartial,
    fallback: styles.dataBadgeFallback,
    weak: styles.dataBadgeWeak,
  };
  return { ...styles.dataQualityBadge, ...(map[tone] || styles.dataBadgeWeak) };
}
