/** MLB team abbreviation → logo URL (ESPN CDN). */

const NAME_TO_ABBR = {
  "arizona diamondbacks": "ari",
  diamondbacks: "ari",
  dbacks: "ari",
  ari: "ari",
  az: "ari",
  "atlanta braves": "atl",
  braves: "atl",
  atl: "atl",
  "baltimore orioles": "bal",
  orioles: "bal",
  bal: "bal",
  "boston red sox": "bos",
  "red sox": "bos",
  bos: "bos",
  "chicago cubs": "chc",
  cubs: "chc",
  chc: "chc",
  "chicago white sox": "chw",
  "white sox": "chw",
  chw: "chw",
  cws: "chw",
  "cincinnati reds": "cin",
  reds: "cin",
  cin: "cin",
  "cleveland guardians": "cle",
  guardians: "cle",
  cle: "cle",
  "colorado rockies": "col",
  rockies: "col",
  col: "col",
  "detroit tigers": "det",
  tigers: "det",
  det: "det",
  "houston astros": "hou",
  astros: "hou",
  hou: "hou",
  "kansas city royals": "kc",
  royals: "kc",
  kc: "kc",
  "los angeles angels": "laa",
  angels: "laa",
  laa: "laa",
  "los angeles dodgers": "lad",
  dodgers: "lad",
  lad: "lad",
  "miami marlins": "mia",
  marlins: "mia",
  mia: "mia",
  "milwaukee brewers": "mil",
  brewers: "mil",
  mil: "mil",
  "minnesota twins": "min",
  twins: "min",
  min: "min",
  "new york mets": "nym",
  mets: "nym",
  nym: "nym",
  "new york yankees": "nyy",
  yankees: "nyy",
  nyy: "nyy",
  "oakland athletics": "oak",
  athletics: "oak",
  oak: "oak",
  "philadelphia phillies": "phi",
  phillies: "phi",
  phi: "phi",
  "pittsburgh pirates": "pit",
  pirates: "pit",
  pit: "pit",
  "san diego padres": "sd",
  padres: "sd",
  sd: "sd",
  "san francisco giants": "sf",
  giants: "sf",
  sf: "sf",
  "seattle mariners": "sea",
  mariners: "sea",
  sea: "sea",
  "st. louis cardinals": "stl",
  "st louis cardinals": "stl",
  cardinals: "stl",
  stl: "stl",
  "tampa bay rays": "tb",
  rays: "tb",
  tb: "tb",
  "texas rangers": "tex",
  rangers: "tex",
  tex: "tex",
  "toronto blue jays": "tor",
  "blue jays": "tor",
  tor: "tor",
  "washington nationals": "wsh",
  nationals: "wsh",
  wsh: "wsh",
  was: "wsh",
};

export function resolveMlbTeamAbbr(team = "") {
  const raw = String(team || "").trim();
  if (!raw) return "";
  const key = raw.toLowerCase().replace(/[^a-z0-9\s.]/g, "").replace(/\s+/g, " ");
  if (NAME_TO_ABBR[key]) return NAME_TO_ABBR[key];
  const upper = raw.toUpperCase();
  if (NAME_TO_ABBR[upper.toLowerCase()]) return NAME_TO_ABBR[upper.toLowerCase()];
  if (/^[A-Z]{2,3}$/.test(upper)) return upper.toLowerCase();
  return "";
}

export function teamLogoUrl(team = "") {
  const abbr = resolveMlbTeamAbbr(team);
  if (!abbr) return "";
  return `https://a.espncdn.com/i/teamlogos/mlb/500/${abbr}.png`;
}
